### Paper 2


Many challenges exist in defining microbial species, mainly a lack of consensus in the academic community, the constant evolution of microbes, and the constant evolution of technology. This is why many schools of thought exist regarding Species Concepts and species definitions. Species definition began with Mayr's Biological Species Concept. As the prominence of microbial life became evident, microbiologists began to favor the new Phylogenetic Species Concept. However, even this system cannot adequately account for the rapid evolution of microbes by horizontal gene transfer (HGT). The ideal species classification system would integrate all fields of consideration, including genetics, ecology, and evolution. 


Mayr's Biological Species Concept is the most widely accepted species concept. It describes species as being organisms which can interbreed. This definition cannot be applied to microbes, as they reproduce asexually. Instead, over the past fifty years, microbial species have been defined based on the level of pairwise DNA-DNA hybridization (DDH) between the DNA of respective genomes. This method entails labelling one strand of DNA, mixing it with an unlabelled DNA sample, then observing the quantity of hybrids that arise. It is expected that sequences with greater similarity will bind at a higher frequency. A 70% DDH value is considered the universal standard within which a species would exist (Konstantinidis 2006). However, many argue that this standard is too liberal and not an accurate representation of organism similarity. In fact, the cut off for species definition was never scientifically justified. It was chosen to match existing species definitions at that time. In the time since this method was developed, genome sequencing has become a much more viable option. The average nucleotide identity (ANI) method measures the extent of nucleotide similarity between coding regions of genomes. A 95% ANI corresponds to the 70% DDH criteria. A single bacterial species may be as diverse as an entire vertebrate order and that the diversity of prokaryotic cells could be largely underestimated in comparison to eukaryotes (Doolittle 2009). This is a clear indication that our current system of prokaryotic species classification is lacking in rigour. This also indicates the importance in designing a new system in concurrence with other proven methods of classification.  


The Phylogenetic Species Concept is based on comparisons of fixed morphological differences between organisms. It is more suitable for microbial species definition than the Biological Species Concept, since it is less restrictive in terms of reproduction, so can be applied to asexual organisms. Microbial phylogenetic trees are constructed using 16S rRNA sequencing data since it is highly conserved and ubiquitous across microbes. In comparison to more recent sequencing technologies, this method is unreliable as it yields poor genetic resolution. For example, Shigella can yield nearly identical 16S rRNA sequences to those of Escherichia coli by the ANI comparison method (Doolittle 2009). However, phylogenetic trees are useful since they can be used to study the divergence of species across time. 


One of the most significant obstacles faced in microbial species definition is HGT. The sheer abundance and rapid replication rate of microbes yields a high frequency of HGT. This is an evolutionary necessity, as frequent mutations increase the diversity and, consequently, the adaptability of populations. This also means that HGT can increase genetic variation in species and distribute phylogenetic pathways so they are no longer characteristic. Consider one study on Streptococcus algalactiae which revealed that each genome acquired by HGT would result in at least thirty new genes in the pan genome. Another study showed that 8-21% of genes in E.coli strains are strain specific (Achtman 2008). These genes, acquired by HGT, are often found in association with genomic islands. This clearly complicates sequence based phylogenetic tree assembly, as a large quantity of genetic information is rapidly exchanged between microbes existing in proximity. Even if an effective, universal microbial species concept is defined, the species themselves will constantly be evolving due to HGT. The enormity of the task of tracking such changes could be mitigated by focusing on known gene islands and tracking the changes in these regions over time. 


Ideally, the future will yield technology where one does not have to make such compromises, and could efficiently sequence whole genomes. This would clearly provide the most comprehensive view of microbial species evolution. Its more than likely that HGT will impact regions outside of the notable gene islands. Whole genome sequencing would also be useful in incorporating ecotype definitions into our microbial species concept, since ecologically relevant genes would also be considered (Konstantinidis 2006). 


It is necessary to have a universal definition for a microbial species. This allows for consolidation of knowledge and effective information sharing, ultimately promoting further advances in science and technology. The species themselves and the technologies we use to define them are always sharing. It is important that this information be clearly communicated across all parties involved in this type of research, so as to facilitate further development in the field. 


##### References  
Achtman M, Wagner M. 2008. Microbial diversity and the genetic nature of microbial species. Nature Reviews Microbiology. 6:431-440. doi: 1038/nrmicro1872.  

Doolittle WF, Zhaxybayeva O. 2009. On the origin of prokaryotic species. 19:744-756. doi:10.1101/gr.086645.108.  

Konstantinidis et al. 2006. The bacterial species definition in the genomic era. Proc Natl Acad Sci USA.361(1475):1929-1940. doi:10.1098/rstb.2006.1920. 
