### Paper 1


Microbial life can life easily without humans, who themselves could not survive without the global catalysis and environmental transformations provided by microbes. Their sheer abundance, resilience and adaptability coupled with the vital reactions they conduct render them essential and not realistically replaceable. Specifically, microbes are responsible for the Earth's atmospheric oxygen concentration and play a number of indispensable roles in the nitrogen cycle. In addition, without microbial life, humans would likely be driven into famine due to the resulting loss in food sources such as seafood, legumes, and ruminant mammals. Finally, this paper will describe how microbes will be integral components in re-establishing stability on earth, in the aftermath of industrialization. 


The oldest evidence for life on earth comes from microbial fossils dated at 3.8Ga. Cyanobacteria are universally believed to be responsible for the Earth's initial rise in atmosphere oxygen at 3Ga, ultimately leading to the emergence of plant and animal life forms (Nisbet 2001). Cyanobacteria and microscopic algae continue to supply oxygen to the atmosphere. Although plants are capable of conducting photosynthesis, respiration and decay negate the effects of photosynthesis by plants on the atmospheric oxygen concentration. On the other hand, marine photosynthesis by eukaryotic algae results in a net production of oxygen in the atmosphere since 0.1% of oceanic organic matter is buried in sediments (Kasting 2002). This is the oxygen that humans rely on for respiration. Establishing the oxygen content in the present atmosphere, marine eukaryotic algae is evidently indispensable to human life on earth. If microbes ceased to exist, humans would not be able to respire, and so would not survive. 


In regards to the nitrogen cycle, microbes are likewise essential. Nitrogen fixing microbes are able to provide the activation energy needed to break nitrogen bonds using enzymes like nitrogenase. Humans require fixed nitrogen to use as building blocks for essential macromolecules, such as amino acids and nucleic acids. Therefore, we cannot survive without nitrogen fixing prokaryotic bacteria. Denitrifying bacteria are play a significant role in maintaining productivity in anoxic deep ocean environments. It is worth acknowledging that, in theory, certain nitrogen containing compounds in the nitrogen cycle could be reduced to ammonium at extremely high temperatures and in the presence of certain forms of iron. If such a reaction were to be actively taking place on Earth, one would anticipate it occurred in hydrothermal vent systems. However, no such process has been observed in these locations. The lack of abiotic nitrogen cycling in even the most extreme of environments reaffirms our dependency on microbes (Canfield 2010). 


Microbial life also indirectly contributes to human life by sustaining life in other organisms. This is especially relevant in food sources such as seafood, legumes and ruminant mammals. The microbial loop sustains the marine food web by mineralizing dissolved nutrients, including dissolved organic carbon. These nutrients have large scale ecological consequences, as they are ultimately incorporated into seafood. Without microbes, the dissolved nutrients would sink to the bottom of the ocean and the energy of these substances would be inaccessible to larger marine life.


Rhizobacteria is a nitrogen fixing bacteria that exists in symbiosis with legumes. It results in increased nitrogen fixation, serving as the main source of nitrogen for plants. Rhizobacteria has been identified in arid environments, suggesting its significance in maintaining sustainable crop yields in times of recurring climate instability and decreased availability of arable land (Ahran 1999). Therefore, humans are likely to become increasingly reliant on microbes for food production as the climate continues to change. 


Ruminants are mammals who acquire nutrients by digesting plant based materials in specialized chambers of the stomach. These chambers contain cellulose digesting bacterial symbionts. Ruminants, including cattle and goats, are farmed for meat and animal products in food production. In the absence of symbiotic microorganisms, these mammals would be severely limited in their capacity to digest food. This would decrease the efficiency of food production significantly. One could imagine a humanity without either seafood, or legumes, or ruminant mammal products. However, the loss of microbial life would result in the simultaneous loss of not just these three food sources, but many others as well. It is simply unreasonable to assume that humans will have the capacity to engineer food products without one of the most fundamental components. 


It is predicted that humanity is driving the Earth into a period of instability. Rockstrom describes the stability of the Earth in terms of "planetary boundaries" which, if crossed, could shift Earth subsystems into a new state. Human actions are the most significant factor in global environmental change at present. However, this change is an unintentional consequence of industrial and agricultural practices. Before the rise of civilization, changes in atmospheric reactions and geological processes occurred naturally over long periods of time in a regulated state. The emergence and development of industrialization, coupled with the expansion of agricultural practices in recent years has disrupted natural cycles. Global warming from greenhouse gas emissions and eutrophication due to nitrogen discharge from farming land are challenging planetary stability. Humans will be reliant on the adaptability of microbiomes to re-establish equilibrium. Microbes have survived since the dawn of life due to their resilience and adaptability. Their high replication rate and abundance enables them to respond to change rapidly and on an immense scale. This change occurs faster and on larger scales than human technology. Simply consider how rapidly antibiotic resistance arises in respond to antibiotics. It is for this reason that microbes must be present in order for life to continue on earth (Rockstrom 2009).


The quantity of microbial life on earth unfathomably vast. For example There is an estimated 10^30^ prokaryotic cells on earth, and around 13x10^28^ bacterial cells in the ocean (Whiteman 1998). Each of these cells is continuously metabolizing, contributing to the biogeochemistry of earth. Replacing microbial functions would have to scale accordingly. It would not be energetically possible to replace even just a sample of essential reactions described in this paper. It is in human nature to perceive the world from an anthropocentric perspective. Humans have managed to quantify the drastic alterations we have instigated in the environment. This has been used as evidence to the power and intelligence of humanity. It has led us to believe that we have the ability to manipulate all aspects of Earth's environment when, in fact, our excessive lifestyle has repercussions beyond our control. The reality is that the existence of humanity has been fundamentally reliant on microbial life, since the dawn of civilization. 

##### References  
Canfield DE et al. 2010. The evolution and future of earth's nitrogen cycle. Science. 330:192. doi: 10.1126/science.1186120.  

Kasting JF, and Siefert JL. 2002. Life and the Evolution of Earth's Atmosphere. Science. 296(5570):1066-1068. doi: 10.1126/science.1071184.  

Nisbet EG, Sleep NH. 2001. The habitat and nature of early life. Nature. 409:1083-1091. doi:10.1038/35059210.  


Rockstrom et al. 2009. A safe operating space for humanity. Nature. 461:472-475. doi:10.1038/461472a.  

Whitman WB, Coleman DC, and Wiebe WJ. 1998. Prokaryotes: The unseen majority. Proc Natl Acad Sci USA. 95(12):6578-6583. PMC33863.  
