### Problem Set 01
[Whitman *et al* 1998](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC33863/)

#### Learning Objectives: 
Describe the numerical abundance of microbial life in relation to the ecology and biogeochemistry of Earth systems.

#### Specific Questions:
* What are the primary prokaryotic habitats on Earth and how do they vary with respect to their capacity to support life? Provide a breakdown of total cell abundance for each primary habitat from the tables provided in the text.  
The primary prokaryotic habitats on Earth are aquatic, soil, and oceanic and terrestrial subsurface habitats. These contain 1.181x10^20^, 2.556x10^29^ and 3.8x10^30^ cells respectively. 

* What is the estimated prokaryotic cell abundance in the upper 200 m of the ocean and what fraction of this biomass is represented by marine cyanobacterium including Prochlorococcus? What is the significance of this ratio with respect to carbon cycling in the ocean and the atmospheric composition of the Earth?  
Upper 200m of ocean contains total of 3.6x10^28^ cells. Of this, 2.9x10^27^ cells are marine cyanobacterium. This high ratio of cyanobacterium in the upper 200m of the ocean is significant because cyanobacterium are autotrophic, meaning they assimilate carbon and produce oxygen. 

* What is the difference between an autotroph, heterotroph, and a lithotroph based on information provided in the text?  
An autotroph fixes inorganic carbon. Heterotrophs assimilate inorganic carbon. Lithotrophs use inorganic substrates. 

* Based on information provided in the text and your knowledge of geography what is the deepest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this depth?  
The deepest habitat capable of supporting prokaryotic life is at 3000m-4000m deep. The primary limiting factor at this depth is temperature.

* Based on information provided in the text your knowledge of geography what is the highest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this height?  
The highest habitat capable of supporting prokaryotic life is at 55-77km high (perhaps an overly optimistic estimate). The primary limiting factor is likely access to other organisms and nutrients, or ionizing radiation. 

* Based on estimates of prokaryotic habitat limitation, what is the vertical distance of the Earth’s biosphere measured in km?  
Estimated vertical distance of Earth's biosphere is 58-81km. 

* How was annual cellular production of prokaryotes described in Table 7 column four determined? (Provide an example of the calculation)  
Use estimates of prokaryotic carbon in environment to set limits for turnover rates. The population size multiplied by the yearly turnover should yield the annual cellular production. 

For example: 

(3.6x1028 cells) x (day/16) x (365day/yr) = 8.2x1029cells/year. 

* What is the relationship between carbon content, carbon assimilation efficiency and turnover rates in the upper 200m of the ocean? Why does this vary with depth in the ocean and between terrestrial and marine habitats?  
Carbon assimilation will increase carbon content, and carbon turnover will decrease carbon content. Carbon content likely increases with depth in the ocean because detritus sinks. Assimilation efficiency and turnover rates probably decrease with depth because productivity decreases since sunlight is lacking,  temperature decreases, and pressure increases. The amount of C in prokaryotes much higher in terrestrial versus marine habitats. However, the net primary productivity is higher in marine habitats.

* How were the frequency numbers for four simultaneous mutations in shared genes determined for marine heterotrophs and marine autotrophs given an average mutation rate of 4 x 10^-7^ per DNA replication? (Provide an example of the calculation with units. Hint: cell and generation cancel out)  

Example calculation for upper 200m heterotroph: 

(3.6x10^28^ cells)x(22.8 turnover/year) = 8.2x10^29^ cells/year

(4x10^-7^ mutations/generation)^4^ = 2.56x10^-26^ mutations/generation 

(8.2x10^29^ cells/year)x(2.56x10^-26^ mutations/generation) = 2.1x10^4^ mutations/year 

(8.7x10^3^)/(2.1x10^4^ mutations/year) = 0.4 mutations/hour


* Given the large population size and high mutation rate of prokaryotic cells, what are the implications with respect to genetic diversity and adaptive potential? Are point mutations the only way in which microbial genomes diversify and adapt?  
The large population size and high mutation rate results in an increase in genetic diversity and adaptive potential for prokaryotes. Some methods of diversification include point mutation, plasmid transfer, recombination, etc. 

* What relationships can be inferred between prokaryotic abundance, diversity, and metabolic potential based on the information provided in the text?  
High abundance an rapid replication result in a high mutation rate. High mutation rate causes an increase in diversity of prokaryotes which, in turn, increases the metabolic potential. 