### Evidence Worksheet 02
[Kasting *et al* 2003](http://science.sciencemag.org/content/296/5570/1066)

#### Learning objectives
Comment on the emergence of microbial life and the evolution of Earth systems.

#### Prompt
* Indicate the key events in the evolution of Earth systems at tic marks on the time series.  

4.6Ga - moon formation, oldest dated zircon minerals found 

4.1Ga - late heavy bombardment

3.8Ga - geological evidence for life on earth; photosynthetic fractionation by Rubisco 

3.0Ga -  production of oxygen by cyanobacteria decreases greenhouse gas effect; life on land; glaciation

2.6Ga - moelcular fossil studies show cyanobacteria and eukaryotes present 

2.3Ga - evidence of redbed rock formation 

1.7Ga - begins with glaciation and the emergence of eukaryotes, ends with another global glaciation 

1.0Ga - animals and land plants emerge; followed by gigantism

* Describe the dominant physical and chemical characteristics of Earth systems at waypoints.  

Haden - Water vapour is high in the atmosphere and lot's is lost to space. Rock vapour also present in the atmosphere. Seawater chemistry is controlled by volcanism and reactions with debris. The sun is faint meaning there was either global glaciation or warmth on earth was sustained by the high greenhouse gas content. 

Archaean - Life on earth is now widespread (chemotrophic life). Earth is hot and active with volcanism. Sulphate in hydrothermal systems provides an oxygenation power. 

Proterozoic - There is a rapid rise in oxygen as a result of the rise in biological activity. New rock formations and mineral types arise. 

Phanerozoic - Life on earth is visible. Land plants carry out photosynthesis. The Earth has assumed its present configuration. 


